# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eba161f94a99147403004470f083ebc4aad1cf38a678093efeaf2ca97e65550607e9a21d98d0a2a83c0579dbea6cf759861de576c94114e55b5c5fa9891229d7

test:
  secret_key_base: ad27b8abb1f4083c45a88824fcb1ddf2e51f5764a5dd9f1dd145f71b93cc25afc1460ee2da044a559318fc3c9ba088e41cd8cfd5ce2b7e47e14ba3c1ba504b71

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
